<?php

namespace OC\LouvresBundle\Repository;

/**
 * bookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param string   $value
   * @param int $tickets
   * @return bool    
   */

public function isBooked($bookingDate)
  {
    $sold_tickets = $this->createQueryBuilder('t')
      ->select('SUM(t)')
      ->where('t.bookingDate = :date')
      ->setParameter('date', $bookingDate)
      ->getQuery()
      ->getSingleScalarResult();

    return $sold_tickets;
  }
}
