<?php

namespace OC\LouvresBundle\Repository;

/**
 * bookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bookingRepository extends \Doctrine\ORM\EntityRepository
{
}
