<?php

namespace OC\LouvresBundle\Repository;

/**
 * bookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//class bookingRepository extends \Doctrine\ORM\EntityRepository
//{
//    /**
//   * @param string   $weekDays
//   * @return bool    
//   */
//  public function isClosed($weekDay) 
//    {
//        $closedDays = array('Tuesday', 'Sunday');
//
//        if (preg_match('#'.implode('|', $closedDays).'#', $weekDay)) {
//            
//            return true;
//    }
//  }
//}
